export type CycleStatus = "open" | "drawn";

export interface Spot {
  id: string;
  label: string;
}

/** One registered resident with the history the ranking rule needs. */
export interface Entrant {
  registrationId: string;
  /** Carried for the caller's convenience; the engine never reads it, so a published snapshot may omit it. */
  residentId?: string;
  /**
   * Distance in cycles from the entrant's most recent allocation, counted from the cycle being
   * drawn. `1` means they held a spot last cycle. `null` means never allocated, which ranks first.
   */
  cyclesSinceLastAllocation: number | null;
  lifetimeAllocations: number;
  /** Past registrations in drawn cycles that did not result in an allocation. */
  lifetimeUnsuccessfulRegistrations: number;
}

export interface Allocation {
  registrationId: string;
  spotId: string;
  /** 1-based position in the ranked entrant list. Recorded for transparency. */
  rank: number;
}

export interface DrawInput {
  cycleId: string;
  entrants: readonly Entrant[];
  spots: readonly Spot[];
  /**
   * Cryptographically random value generated by the caller at draw time and stored with the
   * draw. Any string works; the engine only requires that it is non-empty and reproducible.
   */
  seed: string;
}

export interface DrawResult {
  cycleId: string;
  seed: string;
  /** Every entrant in priority order, winners first. */
  ranked: Entrant[];
  allocations: Allocation[];
}
